# Generated by Django 4.0.6 on 2022-07-12 21:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Winemaker',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('location', models.CharField(max_length=100)),
                ('description', models.TextField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Wine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='No Name', max_length=100)),
                ('type', models.CharField(default='No Type', max_length=100)),
                ('grape', models.CharField(default='No Grape', max_length=100)),
                ('country', models.CharField(default='No Country', max_length=100)),
                ('price', models.FloatField(blank=True, default=None, null=True)),
                ('label', models.TextField(null=True)),
                ('link', models.TextField(null=True)),
                ('winemaker', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='wines', to='journal_des_vin.winemaker')),
            ],
        ),
    ]
